# Generated by Django 5.2.1 on 2025-06-04 03:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('students_name', models.CharField(db_index=True, max_length=100)),
                ('students_dob', models.DateField()),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('students_address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10, 'Mobile Number cannot be more than 10 Digits')])),
                ('alternate_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10, 'Mobile Number cannot be more than 10 Digits')])),
                ('admission_year', models.PositiveIntegerField()),
                ('batch_year', models.PositiveIntegerField()),
                ('final_year', models.PositiveIntegerField()),
                ('certificate_upload', models.ImageField(upload_to='certificate')),
                ('marksheet_upload', models.ImageField(upload_to='marksheet')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MARKSHEETS',
                'db_table': 't_marksheet',
            },
        ),
        migrations.CreateModel(
            name='PaperNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heads', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PAPER NUMBER',
                'db_table': 't_paperno',
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heads', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PAPER TYPE',
                'db_table': 't_papertype',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heads', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'STATUS',
                'db_table': 't_status',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heads', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SUBJECTS',
                'db_table': 't_subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('mobile_no', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 't_users',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=100)),
                ('paper_type', models.CharField(max_length=50)),
                ('paper_no', models.CharField(max_length=20)),
                ('full_marks', models.CharField(max_length=20)),
                ('pass_marks', models.CharField(max_length=20)),
                ('marks_secured', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('marksheet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marksheet.marksheet')),
            ],
            options={
                'verbose_name_plural': 'MARKS',
                'db_table': 't_marks',
            },
        ),
    ]
