# Generated by Django 5.2.1 on 2025-06-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='full_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='marks_secured',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='paper_no',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='pass_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='status',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='admission_year',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='batch_year',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='final_year',
        ),
        migrations.AddField(
            model_name='marks',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='credit_earned',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='grade_obtained',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='grade_points',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='sgpa',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='total_credits_earned',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='exam_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='regn_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
