# Generated by Django 5.2.1 on 2025-06-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0002_remove_marks_full_marks_remove_marks_marks_secured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='certificate_upload',
            field=models.FileField(upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='marksheet_upload',
            field=models.FileField(upload_to='marksheet'),
        ),
    ]
