# Generated by Django 5.2.1 on 2025-06-14 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0006_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_name', models.CharField(db_index=True, max_length=100)),
                ('students_dob', models.DateField()),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('students_address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10, 'Mobile Number cannot be more than 10 Digits')])),
                ('alternate_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10, 'Mobile Number cannot be more than 10 Digits')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'STUDENTS PROFILE',
                'db_table': 't_studentsprofile',
            },
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='alternate_no',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='students_address',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='students_dob',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='students_name',
        ),
        migrations.AddField(
            model_name='marksheet',
            name='student_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='marksheet.studentprofile'),
        ),
    ]
