# Generated by Django 5.2.1 on 2025-06-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0007_studentprofile_remove_marksheet_alternate_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='regn_no',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='students_address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='students_dob',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='regn_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(db_index=True, default=None, max_length=20, unique=True),
        ),
    ]
