# Generated by Django 5.2.1 on 2025-06-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0008_remove_marksheet_regn_no_remove_marksheet_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_address',
            field=models.EmailField(default=None, max_length=50, unique=True),
        ),
    ]
