# Generated by Django 5.2.1 on 2025-06-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0010_subjects_semester_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='marksheet.semester'),
        ),
    ]
