# Generated by Django 5.2.1 on 2025-07-03 13:50

import marksheet.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0011_alter_subjects_semester_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='heads',
            field=marksheet.fields.CaseInsensitiveCharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
