# Generated by Django 5.2.1 on 2025-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0012_alter_semester_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='heads',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
