# Generated by Django 5.2.1 on 2025-07-03 15:32

import marksheet.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0013_alter_semester_heads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='heads',
            field=marksheet.fields.CaseInsensitiveCharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
